export interface IMovie {
  id: number;
  title: string;
  rating: number;
}
export const movies: IMovie[] = [
  { id: 1, title: 'American Friends', rating: 1.3 },
  { id: 2, title: 'Sliver', rating: 2.4 },
  { id: 3, title: 'The Roots of Heaven', rating: 4.8 },
  { id: 4, title: 'Musketeers of Pig Alley, The', rating: 1.4 },
  { id: 5, title: 'Hide Your Smiling Faces', rating: 2.4 },
  { id: 6, title: 'Alcina', rating: 3.0 },
  { id: 7, title: 'Clonus Horror, The', rating: 1.4 },
  { id: 8, title: 'Till Human Voices Wake Us', rating: 3.8 },
  { id: 9, title: 'Rosencrantz and Guildenstern Are Undead', rating: 4.9 },
  { id: 10, title: '2 + 2 (Dos más dos)', rating: 4.2 },
  { id: 11, title: 'Closer to the Moon', rating: 3.8 },
  { id: 12, title: 'Red Riding: 1974', rating: 3.1 },
  { id: 13, title: 'Fighting Temptations, The', rating: 2.7 },
  { id: 14, title: 'Taming the Fire (Ukroshcheniye ognya)', rating: 4.2 },
  { id: 15, title: 'Reclaim Your Brain (Free Rainer)', rating: 3.6 },
  { id: 16, title: 'Substance of Fire, The', rating: 2.8 },
  { id: 17, title: 'Touching the Void', rating: 4.7 },
  { id: 18, title: 'Watermark', rating: 1.2 },
  { id: 19, title: 'Epic Movie', rating: 4.6 },
  { id: 20, title: 'Big Bully', rating: 1.3 },
  { id: 21, title: 'Save the Date', rating: 4.0 },
  { id: 22, title: 'Initiation, The', rating: 1.8 },
  { id: 23, title: 'Arrangement, The', rating: 2.5 },
  { id: 24, title: '13 Beloved (13 game sayawng)', rating: 3.8 },
  { id: 25, title: 'Sweet Movie', rating: 3.1 },
  { id: 26, title: 'Hunting Party, The', rating: 2.8 },
  { id: 27, title: 'Above and Beyond', rating: 1.9 },
  {
    id: 28,
    title: 'Black Magic (Meeting at Midnight) (Charlie Chan in Meeting at Midnight) (Charlie Chan in Black Magic)',
    rating: 2.8,
  },
  { id: 29, title: 'Outlaw Josey Wales, The', rating: 4.8 },
  { id: 30, title: 'Rainy Dog (Gokudô kuroshakai)', rating: 4.5 },
  { id: 31, title: 'Scarface', rating: 1.2 },
  { id: 32, title: 'Lucky Luke: The Ballad of the Daltons', rating: 1.9 },
  { id: 33, title: 'Truth or Consequences, N.M.', rating: 3.5 },
  { id: 34, title: 'Stormy Monday', rating: 2.8 },
  { id: 35, title: 'Ace Ventura: Pet Detective', rating: 2.6 },
  { id: 36, title: 'Pigs with a P.38', rating: 2.0 },
  { id: 37, title: 'Honeymooners, The', rating: 2.7 },
  { id: 38, title: 'Sweet Rush (Tatarak)', rating: 2.3 },
  { id: 39, title: 'Hollywood Sex Wars', rating: 3.5 },
  { id: 40, title: 'Halls of Montezuma', rating: 4.4 },
  { id: 41, title: 'Shrek Forever After (a.k.a. Shrek: The Final Chapter)', rating: 1.4 },
  { id: 42, title: 'Crystal Ball, The', rating: 2.1 },
  { id: 43, title: 'Money Talks', rating: 2.4 },
  { id: 44, title: 'Lord of the Rings: The Return of the King, The', rating: 3.9 },
  { id: 45, title: 'Echoes from the Dead (Skumtimmen)', rating: 1.1 },
  { id: 46, title: 'Point Blank', rating: 4.2 },
  { id: 47, title: 'Beijing Taxi', rating: 4.0 },
  { id: 48, title: 'Zodiac', rating: 2.9 },
  { id: 49, title: 'Camp Rock 2: The Final Jam', rating: 2.3 },
  { id: 50, title: 'Comandante', rating: 4.4 },
];
